package com.ejie.x38.test.bean;


import java.math.BigDecimal;
import java.util.Date;

import javax.validation.Valid;
import javax.validation.groups.Default;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.ejie.x38.serialization.JsonDateDeserializer;
import com.ejie.x38.serialization.JsonDateSerializer;
import com.ejie.x38.serialization.JsonNumberDeserializer;
import com.ejie.x38.serialization.JsonNumberSerializer;
import com.ejie.x38.test.validation.constraints.AlumnoDireccion;
import com.ejie.x38.test.validation.group.AlumnoAddValidation;
import com.ejie.x38.test.validation.group.AlumnoEditValidation;
import com.ejie.x38.test.validation.group.AlumnoEjemplo1Validation;
import com.ejie.x38.test.validation.group.AlumnoEjemplo2Validation;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 *  * Alumno generated by UDA, 01-mar-2012 9:33:10.
 * @author UDA
 */
@AlumnoDireccion(groups={AlumnoAddValidation.class, AlumnoEditValidation.class})
public class Alumno  implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
            private BigDecimal id;
            @NotEmpty(message="validacion.required",groups={Default.class, AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo2Validation.class})
            @Length(min=4, message="validacion.minLength", groups={AlumnoAddValidation.class, AlumnoEditValidation.class})
            private String usuario;
            @NotEmpty(message="validacion.required",groups={AlumnoAddValidation.class, AlumnoEjemplo2Validation.class})
            @Length(min=6, message="validacion.minLength", groups={AlumnoAddValidation.class})
            private String password;
            @NotEmpty(message="validacion.required", groups={Default.class,AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo1Validation.class})
            @Length(max=20, message="validacion.maxLength", groups={AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo1Validation.class})
            private String nombre;
            @NotEmpty(message="validacion.required", groups={AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo1Validation.class})
            @Length(max=30, message="validacion.maxLength", groups={AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo1Validation.class})
            private String apellido1;
            @Length(max=30, message="validacion.maxLength", groups={AlumnoAddValidation.class, AlumnoEditValidation.class, AlumnoEjemplo1Validation.class})
            private String apellido2;
            private String sexo;
            private Date fechaNacimiento;
            private String telefono;
            private String email;
            private String idioma;
            @Valid()
            private NoraPais pais;
            private NoraProvincia provincia;
            private NoraAutonomia autonomia;
            private BigDecimal localidad;
            private BigDecimal comarca;
            private NoraMunicipio municipio;
            private NoraCalle calle;
            private String dni;
            private String nombreImagen;
            private String direccion;
            private BigDecimal importeMatricula;
            private byte[] imagen;
            
            private String gender;
            
	/** Method 'Alumno'.
	*
	*/
    public Alumno() {
    }

    /** Method 'Alumno'.
    * @param id BigDecimal
    * @param usuario String
    * @param password String
    * @param nombre String
    * @param apellido1 String
    * @param apellido2 String
    * @param fechaNacimiento Date
    * @param telefono String
    * @param email String
    * @param idioma String
    * @param pais BigDecimal
    * @param provincia BigDecimal
    * @param localidad BigDecimal
    * @param comarca BigDecimal
    * @param municipio BigDecimal
    * @param calle String
    * @param imagen Blob
    */

    /**
	 * Method 'getId'.
	 *
	 * @return BigDecimal
	 */
	
	
	public BigDecimal getId() {
		return this.id;
	}

	public Alumno(BigDecimal id, String usuario, String password,
			String nombre, String apellido1, String apellido2,
			Date fechaNacimiento, String telefono, String email, String idioma, String sexo,
			NoraPais pais, NoraProvincia provincia, NoraAutonomia autonomia, BigDecimal localidad,
			BigDecimal comarca, NoraMunicipio municipio, NoraCalle calle, String dni,
			String nombreImagen, byte[] imagen) {
		super();
		this.id = id;
		this.usuario = usuario;
		this.password = password;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.sexo = sexo;
		this.fechaNacimiento = fechaNacimiento;
		this.telefono = telefono;
		this.email = email;
		this.idioma = idioma;
		this.pais = pais;
		this.provincia = provincia;
		this.autonomia = autonomia;
		this.localidad = localidad;
		this.comarca = comarca;
		this.municipio = municipio;
		this.calle = calle;
		this.dni = dni;
		this.nombreImagen = nombreImagen;
		this.imagen = imagen;
	}

	/**
	 * Method 'setId'.
	 *
	 * @param id BigDecimal
	 * @return
     */
	
	public void setId(BigDecimal id) {
		this.id = id;
	}
    /**
	 * Method 'getUsuario'.
	 *
	 * @return String
	 */
	
	
	public String getUsuario() {
		return this.usuario;
	}

	/**
	 * Method 'setUsuario'.
	 *
	 * @param usuario String
	 * @return
     */
	
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
    /**
	 * Method 'getPassword'.
	 *
	 * @return String
	 */
	@JsonIgnore
	public String getPassword() {
		return this.password;
	}

	/**
	 * Method 'setPassword'.
	 *
	 * @param password String
	 * @return
     */
	@JsonProperty("password")
	public void setPassword(String password) {
		this.password = password;
	}
    /**
	 * Method 'getNombre'.
	 *
	 * @return String
	 */
	
	
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Method 'setNombre'.
	 *
	 * @param nombre String
	 * @return
     */
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
    /**
	 * Method 'getApellido1'.
	 *
	 * @return String
	 */
	
	
	public String getApellido1() {
		return this.apellido1;
	}

	/**
	 * Method 'setApellido1'.
	 *
	 * @param apellido1 String
	 * @return
     */
	
	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}
    /**
	 * Method 'getApellido2'.
	 *
	 * @return String
	 */
	
	
	public String getApellido2() {
		return this.apellido2;
	}

	/**
	 * Method 'setApellido2'.
	 *
	 * @param apellido2 String
	 * @return
     */
	
	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}
    /**
	 * Method 'getFechaNacimiento'.
	 *
	 * @return Date
	 */
	
	@JsonSerialize(using = JsonDateSerializer.class)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	/**
	 * Method 'setFechaNacimiento'.
	 *
	 * @param fechaNacimiento Date
	 * @return
     */
	@JsonDeserialize(using = JsonDateDeserializer.class)
	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}
    /**
	 * Method 'getTelefono'.
	 *
	 * @return String
	 */
	
	
	public String getTelefono() {
		return this.telefono;
	}

	/**
	 * Method 'setTelefono'.
	 *
	 * @param telefono String
	 * @return
     */
	
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
    /**
	 * Method 'getEmail'.
	 *
	 * @return String
	 */
	
	
	public String getEmail() {
		return this.email;
	}

	/**
	 * Method 'setEmail'.
	 *
	 * @param email String
	 * @return
     */
	
	public void setEmail(String email) {
		this.email = email;
	}
    /**
	 * Method 'getIdioma'.
	 *
	 * @return String
	 */
	
	
	public String getIdioma() {
		return this.idioma;
	}

	/**
	 * Method 'setIdioma'.
	 *
	 * @param idioma String
	 * @return
     */
	
	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}
    /**
	 * Method 'getPais'.
	 *
	 * @return BigDecimal
	 */
	
	
	public NoraPais getPais() {
		return this.pais;
	}

	/**
	 * Method 'setPais'.
	 *
	 * @param pais BigDecimal
	 * @return
     */
	
	public void setPais(NoraPais pais) {
		this.pais = pais;
	}
    /**
	 * Method 'getProvincia'.
	 *
	 * @return BigDecimal
	 */
	
	
	public NoraProvincia getProvincia() {
		return this.provincia;
	}

	/**
	 * Method 'setProvincia'.
	 *
	 * @param provincia BigDecimal
	 * @return
     */
	
	public void setProvincia(NoraProvincia provincia) {
		this.provincia = provincia;
	}
    /**
	 * Method 'getLocalidad'.
	 *
	 * @return BigDecimal
	 */
	
	
	public BigDecimal getLocalidad() {
		return this.localidad;
	}

	/**
	 * Method 'setLocalidad'.
	 *
	 * @param localidad BigDecimal
	 * @return
     */
	
	public void setLocalidad(BigDecimal localidad) {
		this.localidad = localidad;
	}
    /**
	 * Method 'getComarca'.
	 *
	 * @return BigDecimal
	 */
	
	
	public BigDecimal getComarca() {
		return this.comarca;
	}

	/**
	 * Method 'setComarca'.
	 *
	 * @param comarca BigDecimal
	 * @return
     */
	
	public void setComarca(BigDecimal comarca) {
		this.comarca = comarca;
	}
    /**
	 * Method 'getMunicipio'.
	 *
	 * @return BigDecimal
	 */
	
	
	public NoraMunicipio getMunicipio() {
		return this.municipio;
	}

	/**
	 * Method 'setMunicipio'.
	 *
	 * @param municipio BigDecimal
	 * @return
     */
	
	public void setMunicipio(NoraMunicipio municipio) {
		this.municipio = municipio;
	}
    /**
	 * Method 'getCalle'.
	 *
	 * @return String
	 */
	
	
	public NoraCalle getCalle() {
		return this.calle;
	}

	/**
	 * Method 'setCalle'.
	 *
	 * @param calle String
	 * @return
     */
	
	public void setCalle(NoraCalle calle) {
		this.calle = calle;
	}
	
    public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	
	public NoraAutonomia getAutonomia() {
		return autonomia;
	}

	public void setAutonomia(NoraAutonomia autonomia) {
		this.autonomia = autonomia;
	}
	
	

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	
	
	public String getNombreImagen() {
		return nombreImagen;
	}

	public void setNombreImagen(String nombreImagen) {
		this.nombreImagen = nombreImagen;
	}
	
	

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	
	@JsonSerialize(using = JsonNumberSerializer.class)
	public BigDecimal getImporteMatricula() {
		return importeMatricula;
	}
	@JsonDeserialize(using = JsonNumberDeserializer.class, as=BigDecimal.class,contentAs=BigDecimal.class)
	public void setImporteMatricula(BigDecimal importeMatricula) {
		this.importeMatricula = importeMatricula;
	}

	/**
	 * Method 'getImagen'.
	 *
	 * @return Blob
	 */
	public byte[] getImagen() {
		return this.imagen;
	}

	/**
	 * Method 'setImagen'.
	 *
	 * @param imagen Blob
	 * @return
     */
	
	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}


	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		result.append(" [ id: ").append(this.id).append(" ]");
		result.append(", [ usuario: ").append(this.usuario).append(" ]");
		result.append(", [ password: ").append(this.password).append(" ]");
		result.append(", [ nombre: ").append(this.nombre).append(" ]");
		result.append(", [ apellido1: ").append(this.apellido1).append(" ]");
		result.append(", [ apellido2: ").append(this.apellido2).append(" ]");
		result.append(", [ fechaNacimiento: ").append(this.fechaNacimiento).append(" ]");
		result.append(", [ telefono: ").append(this.telefono).append(" ]");
		result.append(", [ email: ").append(this.email).append(" ]");
		result.append(", [ idioma: ").append(this.idioma).append(" ]");
		result.append(", [ pais: ").append(this.pais).append(" ]");
		result.append(", [ provincia: ").append(this.provincia).append(" ]");
		result.append(", [ localidad: ").append(this.localidad).append(" ]");
		result.append(", [ comarca: ").append(this.comarca).append(" ]");
		result.append(", [ municipio: ").append(this.municipio).append(" ]");
		result.append(", [ calle: ").append(this.calle).append(" ]");
		result.append("}");
		return result.toString();
	}


}

