/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/

package com.ejie.x38.test.bean;


import java.math.BigDecimal;

/**
 *  * NoraCalle generated by UDA, 16-ene-2012 13:17:19.
 * @author UDA
 */

public class NoraCalle  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    //Clave compuesta
            private BigDecimal id;
            private BigDecimal calleCod;
            private String dsO;
            private String dsE;
            private String provinciaId;
            private String municipioId;
            private String tipoVia;
            private String tipoViaId;
            private String estado;

	/** Method 'NoraCalle'.
	*
	*/
    public NoraCalle() {
    }
   /** Method 'NoraCalle'.
   * @param id Long
   * @param calleCod BigDecimal
   * @param dsO String
   * @param dsE String
   * @param provinciaId String
   * @param municipioId String
   * @param tipoVia String
   * @param tipoViaId String
   * @param estado String
   */
   public NoraCalle(BigDecimal id, BigDecimal calleCod, String dsO, String dsE, String provinciaId, String municipioId, String tipoVia, String tipoViaId, String estado  ) {

           this.id = id;		
           this.calleCod = calleCod;		
           this.dsO = dsO;		
           this.dsE = dsE;		
           this.provinciaId = provinciaId;		
           this.municipioId = municipioId;		
           this.tipoVia = tipoVia;		
           this.tipoViaId = tipoViaId;		
           this.estado = estado;		
    }

	/**
     * Method 'getId'.
     *
     * @return Long
     */
	
	
	public BigDecimal getId() {
		return this.id;
	}
	
	/**
	 * Method 'setId'.
	 *
	 * @param id Long
	 * @return
	 */
	
	public void setId(BigDecimal id) {
		this.id = id;
	}
	/**
     * Method 'getCalleCod'.
     *
     * @return BigDecimal
     */
	
	
	public BigDecimal getCalleCod() {
		return this.calleCod;
	}
	
	/**
	 * Method 'setCalleCod'.
	 *
	 * @param calleCod BigDecimal
	 * @return
	 */
	
	public void setCalleCod(BigDecimal calleCod) {
		this.calleCod = calleCod;
	}
	/**
     * Method 'getDsO'.
     *
     * @return String
     */
	
	
	public String getDsO() {
		return this.dsO;
	}
	
	/**
	 * Method 'setDsO'.
	 *
	 * @param dsO String
	 * @return
	 */
	
	public void setDsO(String dsO) {
		this.dsO = dsO;
	}
	/**
     * Method 'getDsE'.
     *
     * @return String
     */
	
	
	public String getDsE() {
		return this.dsE;
	}
	
	/**
	 * Method 'setDsE'.
	 *
	 * @param dsE String
	 * @return
	 */
	
	public void setDsE(String dsE) {
		this.dsE = dsE;
	}
	/**
     * Method 'getProvinciaId'.
     *
     * @return String
     */
	
	
	public String getProvinciaId() {
		return this.provinciaId;
	}
	
	/**
	 * Method 'setProvinciaId'.
	 *
	 * @param provinciaId String
	 * @return
	 */
	
	public void setProvinciaId(String provinciaId) {
		this.provinciaId = provinciaId;
	}
	/**
     * Method 'getMunicipioId'.
     *
     * @return String
     */
	
	
	public String getMunicipioId() {
		return this.municipioId;
	}
	
	/**
	 * Method 'setMunicipioId'.
	 *
	 * @param municipioId String
	 * @return
	 */
	
	public void setMunicipioId(String municipioId) {
		this.municipioId = municipioId;
	}
	/**
     * Method 'getTipoVia'.
     *
     * @return String
     */
	
	
	public String getTipoVia() {
		return this.tipoVia;
	}
	
	/**
	 * Method 'setTipoVia'.
	 *
	 * @param tipoVia String
	 * @return
	 */
	
	public void setTipoVia(String tipoVia) {
		this.tipoVia = tipoVia;
	}
	/**
     * Method 'getTipoViaId'.
     *
     * @return String
     */
	
	
	public String getTipoViaId() {
		return this.tipoViaId;
	}
	
	/**
	 * Method 'setTipoViaId'.
	 *
	 * @param tipoViaId String
	 * @return
	 */
	
	public void setTipoViaId(String tipoViaId) {
		this.tipoViaId = tipoViaId;
	}
	/**
     * Method 'getEstado'.
     *
     * @return String
     */
	
	
	public String getEstado() {
		return this.estado;
	}
	
	/**
	 * Method 'setEstado'.
	 *
	 * @param estado String
	 * @return
	 */
	
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		//Clave compuesta

		result.append("[ id: ").append(this.id).append(" ]");

		result.append(", [ calleCod: ").append(this.calleCod).append(" ]");

		result.append(", [ dsO: ").append(this.dsO).append(" ]");

		result.append(", [ dsE: ").append(this.dsE).append(" ]");

		result.append(", [ provinciaId: ").append(this.provinciaId).append(" ]");

		result.append(", [ municipioId: ").append(this.municipioId).append(" ]");

		result.append(", [ tipoVia: ").append(this.tipoVia).append(" ]");

		result.append(", [ tipoViaId: ").append(this.tipoViaId).append(" ]");

		result.append(", [ estado: ").append(this.estado).append(" ]");
		result.append("}");
		return result.toString();
	}


}

