/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/

package com.ejie.x38.test.bean;



/**
 *  * NoraMunicipio generated by UDA, 18-ene-2012 11:57:47.
 * @author UDA
 */

public class NoraMunicipio  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    //Clave compuesta
            private String id;
            private String dsO;
            private String provinciaId;
            private String comarcaId;

	/** Method 'NoraMunicipio'.
	*
	*/
    public NoraMunicipio() {
    }
   /** Method 'NoraMunicipio'.
   * @param id String
   * @param dsO String
   * @param provinciaId String
   * @param comarcaId String
   */
   public NoraMunicipio(String id, String dsO, String provinciaId, String comarcaId  ) {

           this.id = id;		
           this.dsO = dsO;		
           this.provinciaId = provinciaId;		
           this.comarcaId = comarcaId;		
    }

	/**
     * Method 'getId'.
     *
     * @return String
     */
	
	
	public String getId() {
		return this.id;
	}
	
	/**
	 * Method 'setId'.
	 *
	 * @param id String
	 * @return
	 */
	
	public void setId(String id) {
		this.id = id;
	}
	/**
     * Method 'getDsO'.
     *
     * @return String
     */
	
	
	public String getDsO() {
		return this.dsO;
	}
	
	/**
	 * Method 'setDsO'.
	 *
	 * @param dsO String
	 * @return
	 */
	
	public void setDsO(String dsO) {
		this.dsO = dsO;
	}
	/**
     * Method 'getProvinciaId'.
     *
     * @return String
     */
	
	
	public String getProvinciaId() {
		return this.provinciaId;
	}
	
	/**
	 * Method 'setProvinciaId'.
	 *
	 * @param provinciaId String
	 * @return
	 */
	
	public void setProvinciaId(String provinciaId) {
		this.provinciaId = provinciaId;
	}
	/**
     * Method 'getComarcaId'.
     *
     * @return String
     */
	
	
	public String getComarcaId() {
		return this.comarcaId;
	}
	
	/**
	 * Method 'setComarcaId'.
	 *
	 * @param comarcaId String
	 * @return
	 */
	
	public void setComarcaId(String comarcaId) {
		this.comarcaId = comarcaId;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		//Clave compuesta

		result.append("[ id: ").append(this.id).append(" ]");

		result.append(", [ dsO: ").append(this.dsO).append(" ]");

		result.append(", [ provinciaId: ").append(this.provinciaId).append(" ]");

		result.append(", [ comarcaId: ").append(this.comarcaId).append(" ]");
		result.append("}");
		return result.toString();
	}


}

