package com.ejie.x38.serialization;

import java.math.BigDecimal;

import org.hdiv.services.SecureIdentifiable;

import com.ejie.x38.util.Constants;

/**
 * MultiPk generated by UDA, 06-sep-2012 8:37:04.
 * @author UDA
 */

public class MultiPk implements java.io.Serializable, SecureIdentifiable<String> {

	private static final long serialVersionUID = 1L;
    //Clave compuesta
	private BigDecimal ida;
	private BigDecimal idb;
	private String nombre;
	private String apellido1;
	private String apellido2;

	/** 
	 * Method 'MultiPk'.
	 */
    public MultiPk() {}
	
   	/** 
    * Method 'MultiPk'.
   	* @param ida BigDecimal
   	* @param idb BigDecimal
   	* @param nombre String
   	* @param apellido1 String
   	* @param apellido2 String
   	*/
   	public MultiPk(BigDecimal ida, BigDecimal idb, String nombre, String apellido1, String apellido2) {
		this.ida = ida;		
		this.idb = idb;		
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
    }

   /** 
    * Method 'MultiPk'.
    * @param ida BigDecimal
    * @param idb BigDecimal
    */    
    public MultiPk(BigDecimal ida, BigDecimal idb) {
         this.ida = ida;
         this.idb = idb;
	}

	/**
     * Method 'getIda'.
     *
     * @return BigDecimal
     */
	
	public BigDecimal getIda() {
		return this.ida;
	}
	
	/**
	 * Method 'setIda'.
	 *
	 * @param ida BigDecimal
	 * @return
	 */
	
	public void setIda(BigDecimal ida) {
		this.ida = ida;
	}
	/**
     * Method 'getIdb'.
     *
     * @return BigDecimal
     */
	
	
	public BigDecimal getIdb() {
		return this.idb;
	}
	
	/**
	 * Method 'setIdb'.
	 *
	 * @param idb BigDecimal
	 * @return
	 */
	
	public void setIdb(BigDecimal idb) {
		this.idb = idb;
	}
    /**
	 * Method 'getNombre'.
	 *
	 * @return String
	 */
	
	
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Method 'setNombre'.
	 *
	 * @param nombre String
	 * @return
     */
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
    /**
	 * Method 'getApellido1'.
	 *
	 * @return String
	 */
	
	
	public String getApellido1() {
		return this.apellido1;
	}

	/**
	 * Method 'setApellido1'.
	 *
	 * @param apellido1 String
	 * @return
     */
	
	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}
    /**
	 * Method 'getApellido2'.
	 *
	 * @return String
	 */
	
	
	public String getApellido2() {
		return this.apellido2;
	}

	/**
	 * Method 'setApellido2'.
	 *
	 * @param apellido2 String
	 * @return
     */
	
	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		//Clave compuesta
		result.append("[ ida: ").append(this.ida).append(" ]");
		result.append(", [ idb: ").append(this.idb).append(" ]");
		result.append(", [ nombre: ").append(this.nombre).append(" ]");
		result.append(", [ apellido1: ").append(this.apellido1).append(" ]");
		result.append(", [ apellido2: ").append(this.apellido2).append(" ]");
		result.append("}");
		return result.toString();
	}
	
	/**
     * Method 'getId'.
     *
     * @return String
     */
	@Override
	public String getId() {
		// Si cambias la constante PK_TOKEN, es posible que en los logs comience a mostrarse el siguiente aviso: La lista de par�metros recibida no es la misma que la aportada.
		return (this.ida.toString() + Constants.PK_TOKEN + this.idb.toString()).replaceAll(" ", "_space_");
	}

	/**
     * Method 'setId'.
     *
     * @return String
     */

	public void setId(String id) {
		if (id != null && !"".equals(id)) {
			id = id.replaceAll("_space_", " ");
			// Si cambias la constante PK_TOKEN, es posible que en los logs comience a mostrarse el siguiente aviso: La lista de par�metros recibida no es la misma que la aportada.
			String[] parts = id.split(Constants.PK_TOKEN);
			ida = new BigDecimal(parts[0]);
			idb = new BigDecimal(parts[1]);
		}
	}
}
