/*
* Copyright 2012 E.J.I.E., S.A.
*
* Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
* Solo podrá usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en
*
* http://ec.europa.eu/idabc/eupl.html
*
* Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
* el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
* SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
* Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
* que establece la Licencia.
*/

package com.ejie.x38.test.bean;



/**
 *  * NoraProvincia generated by UDA, 18-ene-2012 11:57:47.
 * @author UDA
 */

public class NoraProvincia  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
    //Clave compuesta
            private String id;
            private String dsO;
            private NoraAutonomia autonomia;

	/** Method 'NoraProvincia'.
	*
	*/
    public NoraProvincia() {
    }
   /** Method 'NoraProvincia'.
   * @param id String
   * @param dsO String
   * @param autonomiaId String
   */
   public NoraProvincia(String id, String dsO, NoraAutonomia autonomiaId  ) {

           this.id = id;		
           this.dsO = dsO;		
           this.autonomia = autonomiaId;		
    }

	/**
     * Method 'getId'.
     *
     * @return String
     */
	
	
	public String getId() {
		return this.id;
	}
	
	/**
	 * Method 'setId'.
	 *
	 * @param id String
	 * @return
	 */
	
	public void setId(String id) {
		this.id = id;
	}
	/**
     * Method 'getDsO'.
     *
     * @return String
     */
	
	
	public String getDsO() {
		return this.dsO;
	}
	
	/**
	 * Method 'setDsO'.
	 *
	 * @param dsO String
	 * @return
	 */
	
	public void setDsO(String dsO) {
		this.dsO = dsO;
	}
	/**
     * Method 'getAutonomiaId'.
     *
     * @return String
     */
	
	
	public NoraAutonomia getAutonomia() {
		return this.autonomia;
	}
	
	/**
	 * Method 'setAutonomiaId'.
	 *
	 * @param autonomiaId String
	 * @return
	 */
	
	public void setAutonomia(NoraAutonomia autonomia) {
		this.autonomia = autonomia;
	}

	/**
	 * Intended only for logging and debugging.
	 * 
	 * Here, the contents of every main field are placed into the result.
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		result.append(this.getClass().getName()).append(" Object { " ); 
		//Clave compuesta

		result.append("[ id: ").append(this.id).append(" ]");

		result.append(", [ dsO: ").append(this.dsO).append(" ]");

		result.append(", [ autonomiaId: ").append(this.autonomia).append(" ]");
		result.append("}");
		return result.toString();
	}


}

